# Copyright (C) 2026 Moko Consulting <hello@mokoconsulting.tech>
#
# This file is part of a Moko Consulting project.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# FILE INFORMATION
# DEFGROUP: GitHub.Workflow
# INGROUP: MokoStandards.CI
# REPO: https://github.com/mokoconsulting-tech/MokoStandards
# PATH: /templates/workflows/generic/ci.yml
# VERSION: 01.00.00
# BRIEF: Generic continuous integration workflow for multi-language projects
# NOTE: Supports Node.js, Python, PHP, Go, and other common languages

name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev/**
      - rc/**
      - version/**
  pull_request:
    branches:
      - main
      - dev/**
      - rc/**
      - version/**

permissions:
  contents: read

jobs:
  detect-languages:
    name: Detect Project Languages
    runs-on: ubuntu-latest
    outputs:
      has_nodejs: ${{ steps.detect.outputs.has_nodejs }}
      has_python: ${{ steps.detect.outputs.has_python }}
      has_php: ${{ steps.detect.outputs.has_php }}
      has_go: ${{ steps.detect.outputs.has_go }}
      has_ruby: ${{ steps.detect.outputs.has_ruby }}
      has_rust: ${{ steps.detect.outputs.has_rust }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect languages
        id: detect
        run: |
          echo "has_nodejs=$([ -f 'package.json' ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "has_python=$([ -f 'requirements.txt' ] || [ -f 'setup.py' ] || [ -f 'pyproject.toml' ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "has_php=$([ -f 'composer.json' ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "has_go=$([ -f 'go.mod' ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "has_ruby=$([ -f 'Gemfile' ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "has_rust=$([ -f 'Cargo.toml' ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

  nodejs:
    name: Node.js Build & Test
    runs-on: ubuntu-latest
    needs: detect-languages
    if: needs.detect-languages.outputs.has_nodejs == 'true'
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run tests
        run: npm test --if-present

      - name: Build project
        run: npm run build --if-present

  python:
    name: Python Build & Test
    runs-on: ubuntu-latest
    needs: detect-languages
    if: needs.detect-languages.outputs.has_python == 'true'
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run linter (flake8)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true

      - name: Run type checker (mypy)
        run: |
          pip install mypy
          mypy . --ignore-missing-imports || true
        continue-on-error: true

      - name: Run tests with pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov=. --cov-report=xml --cov-report=term

  php:
    name: PHP Build & Test
    runs-on: ubuntu-latest
    needs: detect-languages
    if: needs.detect-languages.outputs.has_php == 'true'
    
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, zip
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP_CodeSniffer
        run: |
          if [ -f "vendor/bin/phpcs" ]; then
            vendor/bin/phpcs --standard=PSR12 src/ || true
          fi
        continue-on-error: true

      - name: Run PHPUnit tests
        run: |
          if [ -f "vendor/bin/phpunit" ]; then
            vendor/bin/phpunit --coverage-text
          fi

  go:
    name: Go Build & Test
    runs-on: ubuntu-latest
    needs: detect-languages
    if: needs.detect-languages.outputs.has_go == 'true'
    
    strategy:
      matrix:
        go-version: ['1.20', '1.21', '1.22']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Build
        run: go build -v ./...

  ruby:
    name: Ruby Build & Test
    runs-on: ubuntu-latest
    needs: detect-languages
    if: needs.detect-languages.outputs.has_ruby == 'true'
    
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run RuboCop
        run: |
          gem install rubocop
          rubocop || true
        continue-on-error: true

      - name: Run tests
        run: bundle exec rake test || bundle exec rspec || true

  rust:
    name: Rust Build & Test
    runs-on: ubuntu-latest
    needs: detect-languages
    if: needs.detect-languages.outputs.has_rust == 'true'
    
    strategy:
      matrix:
        rust-version: [stable, beta]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust ${{ matrix.rust-version }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Run cargo check
        run: cargo check --all-features

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
        continue-on-error: true

      - name: Run cargo test
        run: cargo test --all-features

      - name: Run cargo build
        run: cargo build --release

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [detect-languages, nodejs, python, php, go, ruby, rust, security]
    if: always()
    
    steps:
      - name: Generate summary
        run: |
          echo "### CI Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: $GITHUB_REPOSITORY" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: $GITHUB_REF_NAME" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Languages detected and tested:" >> $GITHUB_STEP_SUMMARY
          echo "- Node.js: ${{ needs.detect-languages.outputs.has_nodejs }}" >> $GITHUB_STEP_SUMMARY
          echo "- Python: ${{ needs.detect-languages.outputs.has_python }}" >> $GITHUB_STEP_SUMMARY
          echo "- PHP: ${{ needs.detect-languages.outputs.has_php }}" >> $GITHUB_STEP_SUMMARY
          echo "- Go: ${{ needs.detect-languages.outputs.has_go }}" >> $GITHUB_STEP_SUMMARY
          echo "- Ruby: ${{ needs.detect-languages.outputs.has_ruby }}" >> $GITHUB_STEP_SUMMARY
          echo "- Rust: ${{ needs.detect-languages.outputs.has_rust }}" >> $GITHUB_STEP_SUMMARY
