# Copyright (C) 2026 Moko Consulting <hello@mokoconsulting.tech>
#
# This file is part of a Moko Consulting project.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Auto-labeling configuration for pull requests
# See: https://github.com/actions/labeler

# Project Type Labels
joomla:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.xml'
      - '**/mod_*.php'
      - '**/plg_*.php'
      - '**/com_*.php'

dolibarr:
  - changed-files:
    - any-glob-to-any-file:
      - '**/core/modules/**'
      - '**/core/triggers/**'
      - '**/core/boxes/**'

generic:
  - changed-files:
    - any-glob-to-any-file: '*'

# Language Labels
php:
  - changed-files:
    - any-glob-to-any-file: '**/*.php'

javascript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.js'
      - '**/*.jsx'

typescript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.ts'
      - '**/*.tsx'

python:
  - changed-files:
    - any-glob-to-any-file: '**/*.py'

css:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.css'
      - '**/*.scss'
      - '**/*.sass'
      - '**/*.less'

# Component Labels
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'
      - 'README*'
      - 'CHANGELOG*'
      - 'CONTRIBUTING*'
      - 'LICENSE*'

ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '**/.gitlab-ci.yml'
      - '**/Jenkinsfile'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
      - '**/.dockerignore'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      - 'test/**'
      - 'spec/**'
      - '**/*.test.*'
      - '**/*.spec.*'

security:
  - changed-files:
    - any-glob-to-any-file:
      - 'SECURITY.md'
      - '.github/workflows/codeql*.yml'
      - '.github/workflows/security*.yml'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/composer.json'
      - '**/composer.lock'
      - '**/requirements.txt'
      - '**/Gemfile*'

config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/.editorconfig'
      - '**/.eslintrc*'
      - '**/.phpcs.xml*'
      - '**/.prettier*'
      - '**/tsconfig.json'
      - '**/.yamllint'

build:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Makefile'
      - '**/build.sh'
      - '**/webpack.config.js'
      - '**/rollup.config.js'
      - '**/vite.config.js'

# Size Labels
size/xs:
  - changed-files:
    - 1-10

size/s:
  - changed-files:
    - 11-30

size/m:
  - changed-files:
    - 31-100

size/l:
  - changed-files:
    - 101-300

size/xl:
  - changed-files:
    - 301-1000

size/xxl:
  - changed-files:
    - 1001+
