# MokoStandards Sync Override Configuration
#
# This file allows repositories to customize which files and scripts
# are synchronized from MokoStandards during bulk updates.
#
# Place this file in your repository root as '.mokostandards-sync.yml'
#
# Format: YAML
# Schema Version: 1.0

# Override sync behavior
sync:
  # Disable all syncing for this repository
  enabled: true
  
  # Files to exclude from sync (even if in DEFAULT_FILES_TO_SYNC)
  exclude_files:
    # - ".github/workflows/release-cycle.yml"
    # - "phpcs.xml"
  
  # Files to include (in addition to defaults)
  include_files:
    # source_path: destination_path
    # ".github/workflow-templates/custom.yml": ".github/workflows/custom.yml"
  
  # Scripts to exclude from sync
  exclude_scripts:
    # - "scripts/maintenance/release_version.py"
  
  # Scripts to include (in addition to defaults)
  include_scripts:
    # - "scripts/custom/my_script.py"
  
  # Files that should never be overwritten (always preserved)
  protected_files:
    - ".gitignore"
    - ".editorconfig"
    # Add repository-specific files to protect
  
  # Branch name for sync updates (default: chore/sync-mokostandards-updates)
  # branch: "chore/custom-sync-branch"
  
  # Commit message template
  # commit_message: "chore: sync from MokoStandards"
  
  # Set to false to disable automatic PR creation
  # create_pr: true

# Repository-specific settings
repository:
  # Standards compliance level (strict, moderate, relaxed)
  # compliance_level: "moderate"
  
  # Skip specific validations
  # skip_validations:
  #   - "file-headers"
  #   - "changelog-format"

# File-specific overrides
file_overrides:
  # Customize behavior for specific files
  # ".github/dependabot.yml":
  #   always_overwrite: false
  #   merge_strategy: "preserve_local"
  
  # ".github/workflows/build.yml":
  #   always_overwrite: true
  #   merge_strategy: "replace"

# Version of this configuration format
config_version: "1.0"
