# MokoStandards Sync Override Configuration
#
# This file prevents the bulk_update_repos.py script from recreating
# "live" workflow files in the MokoStandards repository itself.
# 
# MokoStandards is a template/standards repository, so it should only
# contain workflow templates and MokoStandards-specific automation,
# not the "live" versions of workflows that get synced to other repos.
#
# Format: YAML
# Schema Version: 1.0

# Override sync behavior
sync:
  # Enable syncing (but with exclusions below)
  enabled: true
  
  # Files to exclude from sync
  # These are "live" workflows that should NOT exist in MokoStandards
  # because they are templates that get synced TO other repos
  exclude_files:
    # Workflow files synced from templates - exclude the live versions
    - ".github/workflows/build.yml"  # corresponds to build-universal.yml template
    - ".github/workflows/code-quality.yml"  # corresponds to code-quality.yml template
    - ".github/workflows/dependency-review.yml"  # corresponds to dependency-review.yml template
    - ".github/workflows/deploy-to-dev.yml"  # corresponds to deploy-to-dev.yml template
    - ".github/workflows/release-cycle.yml"  # corresponds to release-cycle.yml template
  
  # Files that should never be overwritten (always preserved)
  protected_files:
    - ".gitignore"
    - ".editorconfig"
    - ".mokostandards-sync.yml"
    # Keep MokoStandards-specific workflows
    - ".github/workflows/standards-compliance.yml"
    - ".github/workflows/changelog_update.yml"
    - ".github/workflows/bulk-repo-sync.yml"
    - ".github/workflows/confidentiality-scan.yml"
    - ".github/workflows/repo-health.yml"
    - ".github/workflows/auto-create-org-projects.yml"
    - ".github/workflows/sync-changelogs.yml"
    # Keep reusable workflows (these are meant to be called, not synced)
    - ".github/workflows/reusable-build.yml"
    - ".github/workflows/reusable-ci-validation.yml"
    - ".github/workflows/reusable-release.yml"
    - ".github/workflows/reusable-php-quality.yml"
    - ".github/workflows/reusable-platform-testing.yml"
    - ".github/workflows/reusable-project-detector.yml"
    # Keep enterprise firewall setup workflow
    - ".github/workflows/enterprise-firewall-setup.yml"

# Repository-specific settings
repository:
  # This is the standards repository itself
  compliance_level: "strict"

# Version of this configuration format
config_version: "1.0"
