# Copyright (C) 2026 Moko Consulting <hello@mokoconsulting.tech>
#
# This file is part of a Moko Consulting project.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# FILE INFORMATION
# DEFGROUP: GitHub.Workflow
# INGROUP: MokoStandards.Terraform
# REPO: https://github.com/mokoconsulting-tech/MokoStandards
# PATH: /templates/workflows/terraform/ci.yml
# VERSION: 01.00.00
# BRIEF: Terraform continuous integration workflow with validation, formatting, and planning
# NOTE: Validates Terraform configuration, checks formatting, and generates plans

name: Terraform CI

on:
	push:
		branches:
			- main
			- dev/**
			- feature/**
		paths:
			- '**.tf'
			- '**.tfvars'
			- '.github/workflows/terraform-ci.yml'
	pull_request:
		branches:
			- main
			- dev/**
		paths:
			- '**.tf'
			- '**.tfvars'

permissions:
	contents: read
	pull-requests: write
	id-token: write  # Required for OIDC authentication

env:
	TF_VERSION: '1.7.0'  # Update to your preferred Terraform version
	TF_WORKING_DIR: '.'  # Update to your terraform directory

jobs:
	terraform-validate:
		name: Terraform Validation
		runs-on: ubuntu-latest
		
		steps:
			- name: Checkout repository
				uses: actions/checkout@v4

			- name: Setup Terraform
				uses: hashicorp/setup-terraform@v3
				with:
					terraform_version: ${{ env.TF_VERSION }}

			- name: Terraform Format Check
				id: fmt
				run: terraform fmt -check -recursive
				working-directory: ${{ env.TF_WORKING_DIR }}
				continue-on-error: true

			- name: Terraform Init
				id: init
				run: terraform init -backend=false
				working-directory: ${{ env.TF_WORKING_DIR }}

			- name: Terraform Validate
				id: validate
				run: terraform validate -no-color
				working-directory: ${{ env.TF_WORKING_DIR }}

			- name: Comment PR - Validation Results
				if: github.event_name == 'pull_request'
				uses: actions/github-script@v7
				with:
					script: |
						const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
						#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
						#### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
						
						<details><summary>Validation Output</summary>
						
						\`\`\`
						${{ steps.validate.outputs.stdout }}
						\`\`\`
						
						</details>
						
						*Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
						
						github.rest.issues.createComment({
							issue_number: context.issue.number,
							owner: context.repo.owner,
							repo: context.repo.repo,
							body: output
						})

			- name: Fail if validation failed
				if: steps.validate.outcome == 'failure'
				run: exit 1

	terraform-plan:
		name: Terraform Plan
		runs-on: ubuntu-latest
		needs: terraform-validate
		if: github.event_name == 'pull_request'
		
		strategy:
			matrix:
				environment: [dev, staging, prod]  # Customize based on your environments
		
		steps:
			- name: Checkout repository
				uses: actions/checkout@v4

			- name: Setup Terraform
				uses: hashicorp/setup-terraform@v3
				with:
					terraform_version: ${{ env.TF_VERSION }}
					terraform_wrapper: false

			# Configure cloud credentials here based on your provider
			# Example for AWS:
			# - name: Configure AWS Credentials
			#   uses: aws-actions/configure-aws-credentials@v4
			#   with:
			#     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
			#     aws-region: us-east-1

			- name: Terraform Init
				run: |
					terraform init \
						-backend-config="key=terraform-${{ matrix.environment }}.tfstate"
				working-directory: ${{ env.TF_WORKING_DIR }}

			- name: Terraform Plan
				id: plan
				run: |
					terraform plan \
						-var-file="environments/${{ matrix.environment }}.tfvars" \
						-no-color \
						-out=tfplan-${{ matrix.environment }}
				working-directory: ${{ env.TF_WORKING_DIR }}
				continue-on-error: true

			- name: Comment PR - Plan Results
				uses: actions/github-script@v7
				with:
					script: |
						const fs = require('fs');
						const plan = fs.readFileSync('${{ env.TF_WORKING_DIR }}/tfplan-${{ matrix.environment }}', 'utf8');
						
						const output = `#### Terraform Plan for \`${{ matrix.environment }}\` 📖\`${{ steps.plan.outcome }}\`
						
						<details><summary>Show Plan</summary>
						
						\`\`\`terraform
						${plan}
						\`\`\`
						
						</details>
						
						*Environment: \`${{ matrix.environment }}\`, Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
						
						github.rest.issues.createComment({
							issue_number: context.issue.number,
							owner: context.repo.owner,
							repo: context.repo.repo,
							body: output
						})

			- name: Upload Plan Artifact
				uses: actions/upload-artifact@v4
				with:
					name: tfplan-${{ matrix.environment }}
					path: ${{ env.TF_WORKING_DIR }}/tfplan-${{ matrix.environment }}
					retention-days: 5

	terraform-security:
		name: Terraform Security Scan
		runs-on: ubuntu-latest
		needs: terraform-validate
		
		steps:
			- name: Checkout repository
				uses: actions/checkout@v4

			- name: Run tfsec
				uses: aquasecurity/tfsec-action@v1.0.3
				with:
					working_directory: ${{ env.TF_WORKING_DIR }}
					soft_fail: true

			- name: Run Checkov
				uses: bridgecrewio/checkov-action@v12
				with:
					directory: ${{ env.TF_WORKING_DIR }}
					framework: terraform
					soft_fail: true
					output_format: sarif
					output_file_path: reports/checkov.sarif

			- name: Upload Checkov Results
				uses: github/codeql-action/upload-sarif@v3
				if: always()
				with:
					sarif_file: reports/checkov.sarif
